// Moved: base rollable abilities now live in src/content/abilities/rolled
// (one file per ability, generated by scripts/gen-rolled-content.ts). This
// module is a re-export bridge that keeps the historic import surface
// (AbilityId, Ability, ABILITY_SETS, getAbility*, rollAbilityId) intact.
import type { PokeType } from "./pokemon-data";
import { ROLLED_SETS, type AbilityId, type RolledAbilityDef } from "../content/abilities/rolled";

export type { AbilityId } from "../content/abilities/rolled";
export type Ability = RolledAbilityDef;

export const ABILITY_SETS: Record<PokeType, [Ability, Ability, Ability]> = ROLLED_SETS;

const BY_ID: Map<AbilityId, Ability> = new Map(
  Object.values(ABILITY_SETS)
    .flat()
    .map((a) => [a.id, a]),
);

export function getAbilityById(id: AbilityId | null | undefined): Ability | null {
  return (id && BY_ID.get(id)) || null;
}

/** Randomly roll one of the primary type's three abilities. */
export function rollAbilityId(pokemonTypes: PokeType[]): AbilityId {
  const setFor = ABILITY_SETS[pokemonTypes[0]];
  return setFor[Math.floor(Math.random() * setFor.length)].id;
}

/**
 * Resolve the partner's ability: the stored roll if present, otherwise the
 * primary type's legacy (first) ability — existing saves keep exactly the
 * ability they've always had.
 */
export function getAbility(pokemonTypes: PokeType[], abilityId?: AbilityId | null): Ability {
  const stored = getAbilityById(abilityId);
  if (stored) return stored;
  return ABILITY_SETS[pokemonTypes[0]][0];
}
