import type { PokeType } from "./pokemon-data";

export interface GymLeader {
  id: string;
  name: string;
  region: "Kanto" | "Johto" | "Hoenn" | "Sinnoh" | "Unova";
  type: PokeType;
  signaturePokemonId: number;
  badge: string;
  badgeIconUrl: string;
  quote: string;
  trainerSpriteId: string;
}

const BADGE = (slug: string) => `/badges/${slug}.png`;

export const GYM_LEADERS: GymLeader[] = [
  // KANTO
  {
    id: "brock",
    name: "Brock",
    region: "Kanto",
    type: "rock",
    signaturePokemonId: 95,
    badge: "Boulder Badge",
    badgeIconUrl: BADGE("boulder"),
    quote: "The best defense is a strong offense! My rocks won't fall easily!",
    trainerSpriteId: "brock",
  },
  {
    id: "misty",
    name: "Misty",
    region: "Kanto",
    type: "water",
    signaturePokemonId: 121,
    badge: "Cascade Badge",
    badgeIconUrl: BADGE("cascade"),
    quote: "My policy is an all-out offensive with water-type Pokémon!",
    trainerSpriteId: "misty",
  },
  {
    id: "lt-surge",
    name: "Lt. Surge",
    region: "Kanto",
    type: "electric",
    signaturePokemonId: 26,
    badge: "Thunder Badge",
    badgeIconUrl: BADGE("thunder"),
    quote: "I'll show you the real power of electric Pokémon!",
    trainerSpriteId: "lt-surge",
  },
  {
    id: "erika",
    name: "Erika",
    region: "Kanto",
    type: "grass",
    signaturePokemonId: 45,
    badge: "Rainbow Badge",
    badgeIconUrl: BADGE("rainbow"),
    quote: "My pleasure to meet you... let us have a quick battle.",
    trainerSpriteId: "erika",
  },
  {
    id: "koga",
    name: "Koga",
    region: "Kanto",
    type: "poison",
    signaturePokemonId: 110,
    badge: "Soul Badge",
    badgeIconUrl: BADGE("soul"),
    quote: "A mere child like you dares to challenge me?",
    trainerSpriteId: "koga",
  },
  {
    id: "sabrina",
    name: "Sabrina",
    region: "Kanto",
    type: "psychic",
    signaturePokemonId: 65,
    badge: "Marsh Badge",
    badgeIconUrl: BADGE("marsh"),
    quote: "I had a vision of your arrival.",
    trainerSpriteId: "sabrina",
  },
  {
    id: "blaine",
    name: "Blaine",
    region: "Kanto",
    type: "fire",
    signaturePokemonId: 126,
    badge: "Volcano Badge",
    badgeIconUrl: BADGE("volcano"),
    quote: "Hah! I am Blaine! My fiery Pokémon will incinerate all challengers!",
    trainerSpriteId: "blaine",
  },
  {
    id: "giovanni",
    name: "Giovanni",
    region: "Kanto",
    type: "ground",
    signaturePokemonId: 112,
    badge: "Earth Badge",
    badgeIconUrl: BADGE("earth"),
    quote: "So! I must say, I am most impressed you got here.",
    trainerSpriteId: "giovanni",
  },
  // JOHTO
  {
    id: "falkner",
    name: "Falkner",
    region: "Johto",
    type: "flying",
    signaturePokemonId: 18,
    badge: "Zephyr Badge",
    badgeIconUrl: BADGE("zephyr"),
    quote: "I'll show you the real power of the magnificent bird Pokémon!",
    trainerSpriteId: "falkner",
  },
  {
    id: "bugsy",
    name: "Bugsy",
    region: "Johto",
    type: "bug",
    signaturePokemonId: 123,
    badge: "Hive Badge",
    badgeIconUrl: BADGE("hive"),
    quote: "I never lose when it comes to bug Pokémon.",
    trainerSpriteId: "bugsy",
  },
  {
    id: "whitney",
    name: "Whitney",
    region: "Johto",
    type: "normal",
    signaturePokemonId: 241,
    badge: "Plain Badge",
    badgeIconUrl: BADGE("plain"),
    quote: "Hi! I'm Whitney! Everyone was into Pokémon, so I got into it too!",
    trainerSpriteId: "whitney",
  },
  {
    id: "morty",
    name: "Morty",
    region: "Johto",
    type: "ghost",
    signaturePokemonId: 94,
    badge: "Fog Badge",
    badgeIconUrl: BADGE("fog"),
    quote: "I see... You possess a great deal of skill.",
    trainerSpriteId: "morty",
  },
  {
    id: "chuck",
    name: "Chuck",
    region: "Johto",
    type: "fighting",
    signaturePokemonId: 62,
    badge: "Storm Badge",
    badgeIconUrl: BADGE("storm"),
    quote: "WAHAHAH! So you've come this far!",
    trainerSpriteId: "chuck",
  },
  {
    id: "jasmine",
    name: "Jasmine",
    region: "Johto",
    type: "steel",
    signaturePokemonId: 208,
    badge: "Mineral Badge",
    badgeIconUrl: BADGE("mineral"),
    quote: "...You came here for a battle... Forgive me, but I will win.",
    trainerSpriteId: "jasmine",
  },
  {
    id: "pryce",
    name: "Pryce",
    region: "Johto",
    type: "ice",
    signaturePokemonId: 221,
    badge: "Glacier Badge",
    badgeIconUrl: BADGE("glacier"),
    quote: "Pokémon have many experiences in their lives, just as we do.",
    trainerSpriteId: "pryce",
  },
  {
    id: "clair",
    name: "Clair",
    region: "Johto",
    type: "dragon",
    signaturePokemonId: 230,
    badge: "Rising Badge",
    badgeIconUrl: BADGE("rising"),
    quote: "I am Clair, the world's best dragon master.",
    trainerSpriteId: "clair",
  },
  // HOENN
  {
    id: "roxanne",
    name: "Roxanne",
    region: "Hoenn",
    type: "rock",
    signaturePokemonId: 299,
    badge: "Stone Badge",
    badgeIconUrl: BADGE("stone"),
    quote: "Allow me to demonstrate the true power of rock Pokémon!",
    trainerSpriteId: "roxanne",
  },
  {
    id: "brawly",
    name: "Brawly",
    region: "Hoenn",
    type: "fighting",
    signaturePokemonId: 297,
    badge: "Knuckle Badge",
    badgeIconUrl: BADGE("knuckle"),
    quote: "I am Brawly, a wave-riding Pokémon trainer!",
    trainerSpriteId: "brawly",
  },
  {
    id: "wattson",
    name: "Wattson",
    region: "Hoenn",
    type: "electric",
    signaturePokemonId: 82,
    badge: "Dynamo Badge",
    badgeIconUrl: BADGE("dynamo"),
    quote: "Wahahahah! Welcome, challenger!",
    trainerSpriteId: "wattson",
  },
  {
    id: "flannery",
    name: "Flannery",
    region: "Hoenn",
    type: "fire",
    signaturePokemonId: 324,
    badge: "Heat Badge",
    badgeIconUrl: BADGE("heat"),
    quote: "Welcome! No, wait, I have to do this differently...",
    trainerSpriteId: "flannery",
  },
  {
    id: "norman",
    name: "Norman",
    region: "Hoenn",
    type: "normal",
    signaturePokemonId: 289,
    badge: "Balance Badge",
    badgeIconUrl: BADGE("balance"),
    quote: "I'm surprised you made it here. I will have to battle you as a gym leader.",
    trainerSpriteId: "norman",
  },
  {
    id: "winona",
    name: "Winona",
    region: "Hoenn",
    type: "flying",
    signaturePokemonId: 334,
    badge: "Feather Badge",
    badgeIconUrl: BADGE("feather"),
    quote: "I am the leader of Fortree Gym, Winona.",
    trainerSpriteId: "winona",
  },
  {
    id: "tate-liza",
    name: "Tate & Liza",
    region: "Hoenn",
    type: "psychic",
    signaturePokemonId: 337,
    badge: "Mind Badge",
    badgeIconUrl: BADGE("mind"),
    quote: "We're Hoenn's only twin gym leaders! We can decipher what the other is thinking!",
    trainerSpriteId: "tate-and-liza",
  },
  {
    id: "wallace",
    name: "Wallace",
    region: "Hoenn",
    type: "water",
    signaturePokemonId: 350,
    badge: "Rain Badge",
    badgeIconUrl: BADGE("rain"),
    quote: "Welcome, I am Wallace. There's something about you...",
    trainerSpriteId: "wallace",
  },
  // SINNOH
  {
    id: "roark",
    name: "Roark",
    region: "Sinnoh",
    type: "rock",
    signaturePokemonId: 408,
    badge: "Coal Badge",
    badgeIconUrl: BADGE("coal"),
    quote: "I'm not going to let you have your way!",
    trainerSpriteId: "roark",
  },
  {
    id: "gardenia",
    name: "Gardenia",
    region: "Sinnoh",
    type: "grass",
    signaturePokemonId: 407,
    badge: "Forest Badge",
    badgeIconUrl: BADGE("forest"),
    quote: "Anyway, that's enough chitchat. Let's get our battle started!",
    trainerSpriteId: "gardenia",
  },
  {
    id: "maylene",
    name: "Maylene",
    region: "Sinnoh",
    type: "fighting",
    signaturePokemonId: 448,
    badge: "Cobble Badge",
    badgeIconUrl: BADGE("cobble"),
    quote: "I am Maylene, the gym leader of Veilstone.",
    trainerSpriteId: "maylene",
  },
  {
    id: "crasher-wake",
    name: "Crasher Wake",
    region: "Sinnoh",
    type: "water",
    signaturePokemonId: 419,
    badge: "Fen Badge",
    badgeIconUrl: BADGE("fen"),
    quote: "Crasher Wake! Crasher Wake! I am one with water!",
    trainerSpriteId: "crasher-wake",
  },
  {
    id: "fantina",
    name: "Fantina",
    region: "Sinnoh",
    type: "ghost",
    signaturePokemonId: 429,
    badge: "Relic Badge",
    badgeIconUrl: BADGE("relic"),
    quote: "Bonjour. I have come from afar to challenge trainers in Sinnoh.",
    trainerSpriteId: "fantina",
  },
  {
    id: "byron",
    name: "Byron",
    region: "Sinnoh",
    type: "steel",
    signaturePokemonId: 411,
    badge: "Mine Badge",
    badgeIconUrl: BADGE("mine"),
    quote: "I am Byron, the gym leader of Canalave!",
    trainerSpriteId: "byron",
  },
  {
    id: "candice",
    name: "Candice",
    region: "Sinnoh",
    type: "ice",
    signaturePokemonId: 460,
    badge: "Icicle Badge",
    badgeIconUrl: BADGE("icicle"),
    quote: "I'm Candice, the gym leader. Bring it on!",
    trainerSpriteId: "candice",
  },
  {
    id: "volkner",
    name: "Volkner",
    region: "Sinnoh",
    type: "electric",
    signaturePokemonId: 405,
    badge: "Beacon Badge",
    badgeIconUrl: BADGE("beacon"),
    quote: "I'm Volkner, the gym leader of Sunyshore.",
    trainerSpriteId: "volkner",
  },
  // UNOVA
  {
    id: "cilan",
    name: "Cilan",
    region: "Unova",
    type: "grass",
    signaturePokemonId: 511,
    badge: "Trio Badge",
    badgeIconUrl: BADGE("trio"),
    quote: "I will battle you using grass-type Pokémon!",
    trainerSpriteId: "cilan",
  },
  {
    id: "lenora",
    name: "Lenora",
    region: "Unova",
    type: "normal",
    signaturePokemonId: 505,
    badge: "Basic Badge",
    badgeIconUrl: BADGE("basic"),
    quote: "Welcome to my Pokémon gym. I'm Lenora.",
    trainerSpriteId: "lenora",
  },
  {
    id: "burgh",
    name: "Burgh",
    region: "Unova",
    type: "bug",
    signaturePokemonId: 542,
    badge: "Insect Badge",
    badgeIconUrl: BADGE("insect"),
    quote: "I'll be using bug Pokémon, naturally.",
    trainerSpriteId: "burgh",
  },
  {
    id: "elesa",
    name: "Elesa",
    region: "Unova",
    type: "electric",
    signaturePokemonId: 587,
    badge: "Bolt Badge",
    badgeIconUrl: BADGE("bolt"),
    quote: "Now it's time to brighten up the stage!",
    trainerSpriteId: "elesa",
  },
  {
    id: "clay",
    name: "Clay",
    region: "Unova",
    type: "ground",
    signaturePokemonId: 530,
    badge: "Quake Badge",
    badgeIconUrl: BADGE("quake"),
    quote: "Now then. We're gonna have us a Pokémon battle.",
    trainerSpriteId: "clay",
  },
  {
    id: "skyla",
    name: "Skyla",
    region: "Unova",
    type: "flying",
    signaturePokemonId: 581,
    badge: "Jet Badge",
    badgeIconUrl: BADGE("jet"),
    quote: "I'm Skyla, the leader of Mistralton Gym!",
    trainerSpriteId: "skyla",
  },
  {
    id: "brycen",
    name: "Brycen",
    region: "Unova",
    type: "ice",
    signaturePokemonId: 615,
    badge: "Freeze Badge",
    badgeIconUrl: BADGE("freeze"),
    quote: "I have grown stronger by training in the harsh cold.",
    trainerSpriteId: "brycen",
  },
  {
    id: "drayden",
    name: "Drayden",
    region: "Unova",
    type: "dragon",
    signaturePokemonId: 612,
    badge: "Legend Badge",
    badgeIconUrl: BADGE("legend"),
    quote: "I'll show you what dragon Pokémon can do.",
    trainerSpriteId: "drayden",
  },
  {
    id: "roxie",
    name: "Roxie",
    region: "Unova",
    type: "poison",
    signaturePokemonId: 544,
    badge: "Toxic Badge",
    badgeIconUrl: BADGE("toxic"),
    quote: "Get ready to feel the venom!",
    trainerSpriteId: "roxie",
  },
  {
    id: "marlon",
    name: "Marlon",
    region: "Unova",
    type: "water",
    signaturePokemonId: 593,
    badge: "Wave Badge",
    badgeIconUrl: BADGE("wave"),
    quote: "Oh, you're a challenger? I'm Marlon, the gym leader.",
    trainerSpriteId: "marlon",
  },
];

export function findGymLeader(id: string | null | undefined): GymLeader | undefined {
  if (!id) return undefined;
  return GYM_LEADERS.find((g) => g.id === id);
}

export function pickRandomGymLeader(defeatedIds: string[]): GymLeader {
  const unbeaten = GYM_LEADERS.filter((g) => !defeatedIds.includes(g.id));
  const pool = unbeaten.length > 0 ? unbeaten : GYM_LEADERS;
  return pool[Math.floor(Math.random() * pool.length)];
}
