// AUTO-GENERATED by scripts/build-trainers.ts. Do not edit.
import data from "./trainer-data.generated.json";
export interface TrainerSprite {
  id: string;
  name: string;
  url: string;
}
export const TRAINER_SPRITES: TrainerSprite[] = data as TrainerSprite[];
