// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const acrobatics: RolledAbilityDef = {
  id: "acrobatics",
  name: "Acrobatics",
  type: "flying",
  description: "+30% damage while at full HP.",
  slot: 2,
};
