// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const adaptable: RolledAbilityDef = {
  id: "adaptable",
  name: "Adaptable",
  type: "normal",
  description: "Starts with 105 HP instead of 100.",
  slot: 0,
};
