// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const aerilate: RolledAbilityDef = {
  id: "aerilate",
  name: "Aerilate",
  type: "flying",
  description: "Speed bonuses are 50% bigger.",
  slot: 1,
};
