// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const amnesia: RolledAbilityDef = {
  id: "amnesia",
  name: "Amnesia",
  type: "psychic",
  description: "Confused and Poisoned need one extra wrong answer to trigger.",
  slot: 2,
};
