// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const berserk: RolledAbilityDef = {
  id: "berserk",
  name: "Berserk",
  type: "dragon",
  description: "+12% damage after your first wrong answer of the battle.",
  slot: 1,
};
