// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const blaze: RolledAbilityDef = {
  id: "blaze",
  name: "Blaze",
  type: "fire",
  description: "+20% damage while below 40% HP.",
  slot: 1,
};
