// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const bulldoze: RolledAbilityDef = {
  id: "bulldoze",
  name: "Bulldoze",
  type: "ground",
  description: "+25% damage when type-disadvantaged.",
  slot: 2,
};
