// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const charge: RolledAbilityDef = {
  id: "charge",
  name: "Charge",
  type: "electric",
  description: "Every correct answer deals +2 damage.",
  slot: 2,
};
