// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const compoundEyes: RolledAbilityDef = {
  id: "compound-eyes",
  name: "Compound Eyes",
  type: "bug",
  description: "Auto-reveals a wrong option on the first and last question of every set.",
  slot: 0,
};
