// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const corrosion: RolledAbilityDef = {
  id: "corrosion",
  name: "Corrosion",
  type: "poison",
  description: "Wrong answers still deal 2 damage to the enemy.",
  slot: 1,
};
