// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const counter: RolledAbilityDef = {
  id: "counter",
  name: "Counter",
  type: "fighting",
  description: "The correct answer right after a wrong one deals +4 damage.",
  slot: 2,
};
