// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const cursedBody: RolledAbilityDef = {
  id: "cursed-body",
  name: "Cursed Body",
  type: "ghost",
  description: "Wrong answers heal back fully if the next question is answered correctly within 5 seconds.",
  slot: 0,
};
