// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const cuteCharm: RolledAbilityDef = {
  id: "cute-charm",
  name: "Cute Charm",
  type: "fairy",
  description: "15% chance to ignore wrong-answer damage entirely.",
  slot: 0,
};
