// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const darkAura: RolledAbilityDef = {
  id: "dark-aura",
  name: "Dark Aura",
  type: "dark",
  description: "+10% damage in Elite Four and Weekly League battles.",
  slot: 2,
};
