// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const dragonDance: RolledAbilityDef = {
  id: "dragon-dance",
  name: "Dragon Dance",
  type: "dragon",
  description: "Base damage grows by +1 with every 5-question round.",
  slot: 2,
};
