// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const evenTempo: RolledAbilityDef = {
  id: "even-tempo",
  name: "Even Tempo",
  type: "normal",
  description: "+2 damage on neutral type matchups.",
  slot: 2,
};
