// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const filter: RolledAbilityDef = {
  id: "filter",
  name: "Filter",
  type: "steel",
  description: "Reduces super-effective wrong-answer damage by 25%.",
  slot: 0,
};
