// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const flameBody: RolledAbilityDef = {
  id: "flame-body",
  name: "Flame Body",
  type: "fire",
  description: "15% chance to ignore wrong-answer damage entirely.",
  slot: 0,
};
