// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const flashFire: RolledAbilityDef = {
  id: "flash-fire",
  name: "Flash Fire",
  type: "fire",
  description: "All correct answers deal +8% damage.",
  slot: 2,
};
