// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const foresight: RolledAbilityDef = {
  id: "foresight",
  name: "Foresight",
  type: "psychic",
  description: "Reveals one wrong option for free on every 5th question.",
  slot: 0,
};
