// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const guts: RolledAbilityDef = {
  id: "guts",
  name: "Guts",
  type: "fighting",
  description: "Correct answers deal +15% damage when below 50% HP.",
  slot: 0,
};
