// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const hex: RolledAbilityDef = {
  id: "hex",
  name: "Hex",
  type: "ghost",
  description: "+30% damage while you are Confused or Poisoned.",
  slot: 2,
};
