// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const hydration: RolledAbilityDef = {
  id: "hydration",
  name: "Hydration",
  type: "water",
  description: "Auto-cures the first Confused status of every battle.",
  slot: 0,
};
