// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const iceBody: RolledAbilityDef = {
  id: "ice-body",
  name: "Ice Body",
  type: "ice",
  description: "Heals 6 HP every 4th correct answer.",
  slot: 1,
};
