// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";
import type { PokeType } from "../../../lib/pokemon-data";
import { adaptable } from "./adaptable";
import { pickup } from "./pickup";
import { evenTempo } from "./even-tempo";
import { flameBody } from "./flame-body";
import { blaze } from "./blaze";
import { flashFire } from "./flash-fire";
import { hydration } from "./hydration";
import { torrent } from "./torrent";
import { swiftSwim } from "./swift-swim";
import { staticAbility } from "./static";
import { voltAbsorb } from "./volt-absorb";
import { charge } from "./charge";
import { leechSeed } from "./leech-seed";
import { synthesis } from "./synthesis";
import { overgrow } from "./overgrow";
import { snowCloak } from "./snow-cloak";
import { iceBody } from "./ice-body";
import { slushRush } from "./slush-rush";
import { guts } from "./guts";
import { noGuard } from "./no-guard";
import { counter } from "./counter";
import { toxic } from "./toxic";
import { corrosion } from "./corrosion";
import { poisonTouch } from "./poison-touch";
import { sandVeil } from "./sand-veil";
import { sandForce } from "./sand-force";
import { bulldoze } from "./bulldoze";
import { tailwind } from "./tailwind";
import { aerilate } from "./aerilate";
import { acrobatics } from "./acrobatics";
import { foresight } from "./foresight";
import { magicGuard } from "./magic-guard";
import { amnesia } from "./amnesia";
import { compoundEyes } from "./compound-eyes";
import { shieldDust } from "./shield-dust";
import { swarm } from "./swarm";
import { sturdy } from "./sturdy";
import { solidRock } from "./solid-rock";
import { stealthRock } from "./stealth-rock";
import { cursedBody } from "./cursed-body";
import { shadowTag } from "./shadow-tag";
import { hex } from "./hex";
import { multiscale } from "./multiscale";
import { berserk } from "./berserk";
import { dragonDance } from "./dragon-dance";
import { intimidate } from "./intimidate";
import { moxie } from "./moxie";
import { darkAura } from "./dark-aura";
import { filter } from "./filter";
import { ironBarbs } from "./iron-barbs";
import { metalworks } from "./metalworks";
import { cuteCharm } from "./cute-charm";
import { pixieDust } from "./pixie-dust";
import { moonblast } from "./moonblast";

export type { RolledAbilityDef, AbilityId } from "./rolled-def";

export const ROLLED_LIST: readonly RolledAbilityDef[] = [
  adaptable,
  pickup,
  evenTempo,
  flameBody,
  blaze,
  flashFire,
  hydration,
  torrent,
  swiftSwim,
  staticAbility,
  voltAbsorb,
  charge,
  leechSeed,
  synthesis,
  overgrow,
  snowCloak,
  iceBody,
  slushRush,
  guts,
  noGuard,
  counter,
  toxic,
  corrosion,
  poisonTouch,
  sandVeil,
  sandForce,
  bulldoze,
  tailwind,
  aerilate,
  acrobatics,
  foresight,
  magicGuard,
  amnesia,
  compoundEyes,
  shieldDust,
  swarm,
  sturdy,
  solidRock,
  stealthRock,
  cursedBody,
  shadowTag,
  hex,
  multiscale,
  berserk,
  dragonDance,
  intimidate,
  moxie,
  darkAura,
  filter,
  ironBarbs,
  metalworks,
  cuteCharm,
  pixieDust,
  moonblast,
];

export const ROLLED_BY_ID: Record<string, RolledAbilityDef> = {
  "adaptable": adaptable,
  "pickup": pickup,
  "even-tempo": evenTempo,
  "flame-body": flameBody,
  "blaze": blaze,
  "flash-fire": flashFire,
  "hydration": hydration,
  "torrent": torrent,
  "swift-swim": swiftSwim,
  "static": staticAbility,
  "volt-absorb": voltAbsorb,
  "charge": charge,
  "leech-seed": leechSeed,
  "synthesis": synthesis,
  "overgrow": overgrow,
  "snow-cloak": snowCloak,
  "ice-body": iceBody,
  "slush-rush": slushRush,
  "guts": guts,
  "no-guard": noGuard,
  "counter": counter,
  "toxic": toxic,
  "corrosion": corrosion,
  "poison-touch": poisonTouch,
  "sand-veil": sandVeil,
  "sand-force": sandForce,
  "bulldoze": bulldoze,
  "tailwind": tailwind,
  "aerilate": aerilate,
  "acrobatics": acrobatics,
  "foresight": foresight,
  "magic-guard": magicGuard,
  "amnesia": amnesia,
  "compound-eyes": compoundEyes,
  "shield-dust": shieldDust,
  "swarm": swarm,
  "sturdy": sturdy,
  "solid-rock": solidRock,
  "stealth-rock": stealthRock,
  "cursed-body": cursedBody,
  "shadow-tag": shadowTag,
  "hex": hex,
  "multiscale": multiscale,
  "berserk": berserk,
  "dragon-dance": dragonDance,
  "intimidate": intimidate,
  "moxie": moxie,
  "dark-aura": darkAura,
  "filter": filter,
  "iron-barbs": ironBarbs,
  "metalworks": metalworks,
  "cute-charm": cuteCharm,
  "pixie-dust": pixieDust,
  "moonblast": moonblast,
};

export const ROLLED_SETS: Record<PokeType, [RolledAbilityDef, RolledAbilityDef, RolledAbilityDef]> = {
  normal: [adaptable, pickup, evenTempo],
  fire: [flameBody, blaze, flashFire],
  water: [hydration, torrent, swiftSwim],
  electric: [staticAbility, voltAbsorb, charge],
  grass: [leechSeed, synthesis, overgrow],
  ice: [snowCloak, iceBody, slushRush],
  fighting: [guts, noGuard, counter],
  poison: [toxic, corrosion, poisonTouch],
  ground: [sandVeil, sandForce, bulldoze],
  flying: [tailwind, aerilate, acrobatics],
  psychic: [foresight, magicGuard, amnesia],
  bug: [compoundEyes, shieldDust, swarm],
  rock: [sturdy, solidRock, stealthRock],
  ghost: [cursedBody, shadowTag, hex],
  dragon: [multiscale, berserk, dragonDance],
  dark: [intimidate, moxie, darkAura],
  steel: [filter, ironBarbs, metalworks],
  fairy: [cuteCharm, pixieDust, moonblast],
};
