// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const intimidate: RolledAbilityDef = {
  id: "intimidate",
  name: "Intimidate",
  type: "dark",
  description: "The enemy starts at 90% HP instead of 100%.",
  slot: 0,
};
