// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const ironBarbs: RolledAbilityDef = {
  id: "iron-barbs",
  name: "Iron Barbs",
  type: "steel",
  description: "All wrong-answer damage is reduced by 3.",
  slot: 1,
};
