// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const leechSeed: RolledAbilityDef = {
  id: "leech-seed",
  name: "Leech Seed",
  type: "grass",
  description: "Heals 2 HP for every correct answer.",
  slot: 0,
};
