// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const magicGuard: RolledAbilityDef = {
  id: "magic-guard",
  name: "Magic Guard",
  type: "psychic",
  description: "Statuses deal no HP damage.",
  slot: 1,
};
