// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const metalworks: RolledAbilityDef = {
  id: "metalworks",
  name: "Metalworks",
  type: "steel",
  description: "Shop items cost 10% less.",
  slot: 2,
};
