// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const moonblast: RolledAbilityDef = {
  id: "moonblast",
  name: "Moonblast",
  type: "fairy",
  description: "+4 damage while on a 3-streak or higher.",
  slot: 2,
};
