// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const moxie: RolledAbilityDef = {
  id: "moxie",
  name: "Moxie",
  type: "dark",
  description: "+1 permanent damage each time you reach a 3-streak (stacks all battle).",
  slot: 1,
};
