// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const multiscale: RolledAbilityDef = {
  id: "multiscale",
  name: "Multiscale",
  type: "dragon",
  description: "Wrong-answer damage is halved while at full HP.",
  slot: 0,
};
