// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const noGuard: RolledAbilityDef = {
  id: "no-guard",
  name: "No Guard",
  type: "fighting",
  description: "+18% damage on every correct answer, but wrong answers hit 2 harder.",
  slot: 1,
};
