// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const overgrow: RolledAbilityDef = {
  id: "overgrow",
  name: "Overgrow",
  type: "grass",
  description: "+12% damage while the enemy is above half HP.",
  slot: 2,
};
