// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const pickup: RolledAbilityDef = {
  id: "pickup",
  name: "Pickup",
  type: "normal",
  description: "Earns 25% more coins from battles.",
  slot: 1,
};
