// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const pixieDust: RolledAbilityDef = {
  id: "pixie-dust",
  name: "Pixie Dust",
  type: "fairy",
  description: "Heals 5 HP every time you reach a 3-streak.",
  slot: 1,
};
