// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const poisonTouch: RolledAbilityDef = {
  id: "poison-touch",
  name: "Poison Touch",
  type: "poison",
  description: "Correct answers poison the enemy for 2 extra damage on the next question.",
  slot: 2,
};
