// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const sandForce: RolledAbilityDef = {
  id: "sand-force",
  name: "Sand Force",
  type: "ground",
  description: "The first two wrong answers each battle don't reset your streak.",
  slot: 1,
};
