// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const sandVeil: RolledAbilityDef = {
  id: "sand-veil",
  name: "Sand Veil",
  type: "ground",
  description: "+2 seconds added to every question timer.",
  slot: 0,
};
