// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const shadowTag: RolledAbilityDef = {
  id: "shadow-tag",
  name: "Shadow Tag",
  type: "ghost",
  description: "The enemy loses 2 HP whenever you take damage.",
  slot: 1,
};
