// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const shieldDust: RolledAbilityDef = {
  id: "shield-dust",
  name: "Shield Dust",
  type: "bug",
  description: "Immune to the Confused status.",
  slot: 1,
};
