// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const slushRush: RolledAbilityDef = {
  id: "slush-rush",
  name: "Slush Rush",
  type: "ice",
  description: "Wrong-answer damage is reduced by 5 when type-disadvantaged.",
  slot: 2,
};
