// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const snowCloak: RolledAbilityDef = {
  id: "snow-cloak",
  name: "Snow Cloak",
  type: "ice",
  description: "The first wrong answer of every battle deals 0 damage.",
  slot: 0,
};
