// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const solidRock: RolledAbilityDef = {
  id: "solid-rock",
  name: "Solid Rock",
  type: "rock",
  description: "No single hit can deal more than 12 damage.",
  slot: 1,
};
