// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const staticAbility: RolledAbilityDef = {
  id: "static",
  name: "Static",
  type: "electric",
  description: "Wrong-answer damage is halved 20% of the time.",
  slot: 0,
};
