// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const stealthRock: RolledAbilityDef = {
  id: "stealth-rock",
  name: "Stealth Rock",
  type: "rock",
  description: "The enemy takes 3 damage at the start of every 5-question round.",
  slot: 2,
};
