// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const sturdy: RolledAbilityDef = {
  id: "sturdy",
  name: "Sturdy",
  type: "rock",
  description: "Survives the first otherwise-fatal hit at 1 HP. Once per battle.",
  slot: 0,
};
