// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const swarm: RolledAbilityDef = {
  id: "swarm",
  name: "Swarm",
  type: "bug",
  description: "+3 damage while on a 3-streak or higher.",
  slot: 2,
};
