// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const swiftSwim: RolledAbilityDef = {
  id: "swift-swim",
  name: "Swift Swim",
  type: "water",
  description: "Speed bonus is never lower than 3.",
  slot: 2,
};
