// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const synthesis: RolledAbilityDef = {
  id: "synthesis",
  name: "Synthesis",
  type: "grass",
  description: "Potions and Super Potions heal 50% more.",
  slot: 1,
};
