// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const tailwind: RolledAbilityDef = {
  id: "tailwind",
  name: "Tailwind",
  type: "flying",
  description: "+20% damage on the first 3 questions of every battle.",
  slot: 0,
};
