// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const torrent: RolledAbilityDef = {
  id: "torrent",
  name: "Torrent",
  type: "water",
  description: "Heals 10 HP the first time you drop below 30% HP each battle.",
  slot: 1,
};
