// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const toxic: RolledAbilityDef = {
  id: "toxic",
  name: "Toxic",
  type: "poison",
  description: "Immune to Poisoned, and Confused cures after 1 correct answer.",
  slot: 0,
};
