// GENERATED by scripts/gen-rolled-content.ts — do not hand-edit.
import type { RolledAbilityDef } from "./rolled-def";

export const voltAbsorb: RolledAbilityDef = {
  id: "volt-absorb",
  name: "Volt Absorb",
  type: "electric",
  description: "Answers within 5 seconds deal +3 damage.",
  slot: 1,
};
